dist: trusty
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - 'pypy'
install:
  - pip install -r requirements.txt
  - pip install coveralls coverage
  - pip install -U setuptools
  - pip install pytest --upgrade
script:
  - python setup.py install
  - coverage run --source flask_rest_jsonapi -m pytest -v
after_success:
  - coveralls
